Remove deprecated license classifiers
These should not have been added in #15, since such classifiers are
deprecated according to the error message:

    InvalidConfigError: License classifiers have been superseded by license expressions (see https://peps.python.org/pep-0639/). Please remove:

    License :: OSI Approved :: Zero-Clause BSD (0BSD)

This removes, but leaves over classifiers added in #15 intact.